# Generated by Django 5.1.7 on 2025-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
