# Generated by Django 5.1.7 on 2025-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_studentapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=100),
        ),
    ]
