# Generated by Django 5.1.7 on 2025-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_studentapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
