# Generated by Django 5.1.7 on 2025-03-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_studentapplication_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='application_type',
            field=models.CharField(choices=[('General', 'General'), ('Certificate Issue Request', 'Certificate Issue Request')], default='General', max_length=100),
        ),
    ]
