# Generated by Django 5.1.5 on 2025-01-21 17:54

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=5, null=True)),
                ('program', models.CharField(choices=[('BCA', 'Bachelor of Computer Applications'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('BBA LLB', 'Bachelor of Business Administration and Bachelor of Legislative Law'), ('LLB', 'Bachelor of Legislative Law')], max_length=50)),
                ('semester', models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8')], default='1', max_length=10)),
                ('course_start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('course_duration', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('caste', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='GEN', max_length=20)),
                ('religion', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('pan', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='PAN must follow the format: 5 letters, 4 digits, 1 letter (e.g., ABCDE1234F).', regex='^[A-Z]{5}\\d{4}[A-Z]{1}$')])),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar must be exactly 12 digits.', regex='^\\d{12}$')])),
                ('abc_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('country', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('TC', 'Transfer Certificate'), ('CC', 'Character Certificate'), ('BC', 'Bonafide Certificate')], max_length=2)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('details', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='authentication.user')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
