# Generated by Django 5.1.5 on 2025-02-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_certificate_approval_status_certificate_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
