# Generated by Django 5.1.5 on 2025-02-09 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='caste',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='street_address',
            new_name='current_address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='fathers_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='country',
            new_name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.AddField(
            model_name='student',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='erp',
            field=models.CharField(default='0221BCA000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_contact',
            field=models.CharField(default=121212, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_contact',
            field=models.CharField(default=None, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='permament_address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
