# Generated by Django 5.1.5 on 2025-02-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_added_on_student_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='permament_address',
            new_name='permanent_address',
        ),
    ]
