# Generated by Django 5.1.5 on 2025-02-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_permament_address_student_permanent_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
